### ISSUE TITLE
Am I Able to change remote settings from Atem CHOP?

### ISSUE THREAD

**Issue by talorno** [camikura/touchdesigner-atem-chop#1]
Hi!

Importing your CHOP in TouchDesigner i can correctly connect to the ATEM hardware but it seems like i'm not able to send commands (e.g. change preview and program, do Take, and so on), bc it seems that the CHOP has no editable channels even if looking at the source code i can see it should be able to do it....

**Comment by camikura** [comment]
Hi talorno

Sorry for the confusion and lack of document.
I've updated the README and uploaded a movie showing how to use it.

**Comment by talorno** [comment]
you're the man!! 

Thanks a lot
